Attribute VB_Name = "KernelFormSetup2"
Option Explicit

' Copyright (c) 2026 Ethan Genteman. All rights reserved.
' Proprietary and confidential. Unauthorized use prohibited.
' See LICENSE.txt for terms.

' KernelFormSetup2.bas
' Purpose: WorkspaceExplorer form creation + event code.
' Split from KernelFormSetup.bas (AD-09: module size limit).

Public Sub CreateWorkspaceExplorer()
    Dim comp As Object
    Set comp = ThisWorkbook.VBProject.VBComponents.Add(3)
    comp.Name = "WorkspaceExplorer"
    Dim d As Object: Set d = comp.designer
    ' Config-driven title from branding
    Dim wsTitle As String
    wsTitle = KernelConfig.GetBrandingSetting("CompanyName")
    If Len(wsTitle) = 0 Then wsTitle = "RDK"
    comp.Properties("Caption") = wsTitle & " -- Workspaces"
    comp.Properties("Width") = 500
    comp.Properties("Height") = 360

    ' --- Top bar: workspace selector ---
    AddOptionButton d, "optActive", "Active", 12, 8, 60, 18
    AddOptionButton d, "optArchived", "Archived", 76, 8, 70, 18
    AddLabel d, "lblWorkspace", "Workspace:", 160, 10, 58, 18
    AddComboBox d, "cmbWorkspace", 222, 8, 200, 20
    AddButton d, "btnNewWS", "New", 430, 8, 50, 22

    ' --- Workspace metadata ---
    AddLabel d, "lblWSMeta", "", 12, 32, 470, 14
    Dim metaCtrl As Object
    Set metaCtrl = d.Controls("lblWSMeta")
    metaCtrl.Font.Size = 8
    metaCtrl.ForeColor = &H808080

    ' --- Version list (3 columns: Version, Date, Description) ---
    AddLabel d, "lblVersions", "Versions:", 12, 50, 60, 14
    AddListBox d, "lstVersions", 12, 66, 470, 180, 6, "50;130;200;50;90;60"

    ' --- Active indicator ---
    AddLabel d, "lblActive", "", 12, 250, 470, 14
    Dim actCtrl As Object
    Set actCtrl = d.Controls("lblActive")
    actCtrl.Font.Size = 8
    actCtrl.Font.Italic = True
    actCtrl.ForeColor = &HC47244

    ' --- Primary action buttons (y=270) ---
    AddButton d, "btnSave", "Save", 12, 270, 70, 28
    AddButton d, "btnLoadAll", "Load", 88, 270, 70, 28
    AddButton d, "btnPin", "Pin / Unpin", 164, 270, 80, 28
    AddButton d, "btnInspect", "Inspect", 250, 270, 70, 28
    AddButton d, "btnMore", "More...", 326, 270, 70, 28

    ' --- Hidden buttons (called from More popup, not on main form) ---
    ' These are needed for the code handlers but placed off-screen
    AddButton d, "btnBranch", "", -100, -100, 1, 1
    AddButton d, "btnArchive", "", -100, -100, 1, 1
    AddButton d, "btnDelete", "", -100, -100, 1, 1
    AddButton d, "btnRename", "", -100, -100, 1, 1
    AddButton d, "btnDesc", "", -100, -100, 1, 1
    AddButton d, "btnCompare", "", -100, -100, 1, 1
    AddButton d, "btnSortDate", "", -100, -100, 1, 1
    AddButton d, "btnSortName", "", -100, -100, 1, 1

    AddWorkspaceExplorerCode comp.CodeModule
End Sub

Public Sub AddWorkspaceExplorerCode(ByVal cm As Object)
    If cm.CountOfLines > 0 Then cm.DeleteLines 1, cm.CountOfLines
    Dim n As Long: n = 1
    n = IL(cm, n, "Option Explicit")
    n = IL(cm, n, "Private m_sortByDate As Boolean")
    n = IL(cm, n, "Private m_activeWS As String")
    n = IL(cm, n, "Private m_activeVer As String")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub UserForm_Initialize()")
    n = IL(cm, n, "    m_sortByDate = True")
    n = IL(cm, n, "    optActive.Value = True")
    n = IL(cm, n, "    m_activeWS = """"")
    n = IL(cm, n, "    m_activeVer = """"")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    UpdateButtonStates")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub optActive_Click()")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    UpdateButtonStates")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub optArchived_Click()")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    UpdateButtonStates")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub UpdateButtonStates()")
    n = IL(cm, n, "    Dim isArchive As Boolean")
    n = IL(cm, n, "    isArchive = optArchived.Value")
    n = IL(cm, n, "    btnSave.Enabled = Not isArchive")
    n = IL(cm, n, "    btnNewWS.Enabled = Not isArchive")
    n = IL(cm, n, "    btnBranch.Enabled = Not isArchive")
    n = IL(cm, n, "    If isArchive Then")
    n = IL(cm, n, "        btnArchive.Caption = ""Restore""")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        btnArchive.Caption = ""Archive""")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub LoadWorkspaceList()")
    n = IL(cm, n, "    cmbWorkspace.Clear")
    n = IL(cm, n, "    lstVersions.Clear")
    n = IL(cm, n, "    lblWSMeta.Caption = """"")
    n = IL(cm, n, "    On Error Resume Next")
    n = IL(cm, n, "    Dim root As String")
    n = IL(cm, n, "    root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces""")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive""")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    If Dir(baseDir, vbDirectory) = """" Then Exit Sub")
    n = IL(cm, n, "    Dim fso As Object")
    n = IL(cm, n, "    Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "    If Not fso.FolderExists(baseDir) Then Exit Sub")
    n = IL(cm, n, "    Dim subFld As Object")
    n = IL(cm, n, "    For Each subFld In fso.GetFolder(baseDir).SubFolders")
    n = IL(cm, n, "        If Left(subFld.Name, 1) <> ""_"" And subFld.Name <> ""archive"" Then")
    n = IL(cm, n, "            Dim displayName As String")
    n = IL(cm, n, "            If KernelWorkspace.IsWorkspacePinned(subFld.Name) Then")
    n = IL(cm, n, "                displayName = ""[P] "" & subFld.Name")
    n = IL(cm, n, "            Else")
    n = IL(cm, n, "                displayName = subFld.Name")
    n = IL(cm, n, "            End If")
    n = IL(cm, n, "            cmbWorkspace.AddItem displayName")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "    Next subFld")
    n = IL(cm, n, "    Set fso = Nothing")
    n = IL(cm, n, "    On Error GoTo 0")
    n = IL(cm, n, "    If cmbWorkspace.ListCount > 0 Then cmbWorkspace.ListIndex = 0")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Function GetRealWSName() As String")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        GetRealWSName = """"")
    n = IL(cm, n, "        Exit Function")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim raw As String: raw = cmbWorkspace.List(cmbWorkspace.ListIndex)")
    n = IL(cm, n, "    If Left(raw, 4) = ""[P] "" Then")
    n = IL(cm, n, "        GetRealWSName = Mid(raw, 5)")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        GetRealWSName = raw")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "End Function")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub cmbWorkspace_Change()")
    n = IL(cm, n, "    LoadVersionList")
    n = IL(cm, n, "    UpdateWSMeta")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub UpdateWSMeta()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        lblWSMeta.Caption = """"")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    Dim root As String")
    n = IL(cm, n, "    root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\"" & wsName")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive\"" & wsName")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    On Error Resume Next")
    n = IL(cm, n, "    Dim jsonPath As String")
    n = IL(cm, n, "    jsonPath = baseDir & ""\workspace.json""")
    n = IL(cm, n, "    Dim created As String: created = """"")
    n = IL(cm, n, "    Dim lastSaved As String: lastSaved = """"")
    n = IL(cm, n, "    If Dir(jsonPath) <> """" Then")
    n = IL(cm, n, "        created = KernelFormHelpers.ReadJsonField(jsonPath, ""created"")")
    n = IL(cm, n, "        lastSaved = KernelFormHelpers.ReadJsonField(jsonPath, ""lastSaved"")")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim metaTxt As String")
    n = IL(cm, n, "    metaTxt = ""Created: "" & created & ""  |  Versions: "" & lstVersions.ListCount & ""  |  Last saved: "" & lastSaved")
    n = IL(cm, n, "    If KernelWorkspace.IsWorkspacePinned(wsName) Then")
    n = IL(cm, n, "        metaTxt = metaTxt & ""  |  Pinned""")
    n = IL(cm, n, "        btnPin.Caption = ""Unpin""")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        btnPin.Caption = ""Pin""")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    lblWSMeta.Caption = metaTxt")
    n = IL(cm, n, "    On Error GoTo 0")
    n = IL(cm, n, "    If StrComp(wsName, m_activeWS, vbTextCompare) = 0 And Len(m_activeWS) > 0 Then")
    n = IL(cm, n, "        lblActive.Caption = ""Currently loaded: "" & m_activeWS & "" "" & m_activeVer")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        lblActive.Caption = """"")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub LoadVersionList()")
    n = IL(cm, n, "    lstVersions.Clear")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then Exit Sub")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    On Error Resume Next")
    n = IL(cm, n, "    Dim root As String")
    n = IL(cm, n, "    root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\"" & wsName")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive\"" & wsName")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    If Dir(baseDir, vbDirectory) = """" Then Exit Sub")
    n = IL(cm, n, "    Dim fso As Object")
    n = IL(cm, n, "    Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "    If Not fso.FolderExists(baseDir) Then Exit Sub")
    n = IL(cm, n, "    Dim vFolders() As String")
    n = IL(cm, n, "    Dim vCount As Long: vCount = 0")
    n = IL(cm, n, "    Dim subFld As Object")
    n = IL(cm, n, "    For Each subFld In fso.GetFolder(baseDir).SubFolders")
    n = IL(cm, n, "        If Left(subFld.Name, 1) = ""v"" And Len(subFld.Name) >= 2 Then")
    n = IL(cm, n, "            vCount = vCount + 1")
    n = IL(cm, n, "            ReDim Preserve vFolders(1 To vCount)")
    n = IL(cm, n, "            vFolders(vCount) = subFld.Name")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "    Next subFld")
    n = IL(cm, n, "    If vCount > 1 Then")
    n = IL(cm, n, "        Dim a As Long, b As Long, tmp As String")
    n = IL(cm, n, "        For a = 1 To vCount - 1")
    n = IL(cm, n, "            For b = a + 1 To vCount")
    n = IL(cm, n, "                If vFolders(b) > vFolders(a) Then")
    n = IL(cm, n, "                    tmp = vFolders(a): vFolders(a) = vFolders(b): vFolders(b) = tmp")
    n = IL(cm, n, "                End If")
    n = IL(cm, n, "            Next b")
    n = IL(cm, n, "        Next a")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim vi As Long")
    n = IL(cm, n, "    For vi = 1 To vCount")
    n = IL(cm, n, "        Dim vDir As String")
    n = IL(cm, n, "        vDir = baseDir & ""\"" & vFolders(vi)")
    n = IL(cm, n, "        Dim mPath As String")
    n = IL(cm, n, "        mPath = vDir & ""\manifest.json""")
    n = IL(cm, n, "        Dim vDate As String: vDate = """"")
    n = IL(cm, n, "        Dim vDesc As String: vDesc = """"")
    n = IL(cm, n, "        Dim vStale As String: vStale = """"")
    n = IL(cm, n, "        Dim vLastRun As String: vLastRun = """"")
    n = IL(cm, n, "        Dim vDuration As String: vDuration = """"")
    n = IL(cm, n, "        If Dir(mPath) <> """" Then")
    n = IL(cm, n, "            vDate = KernelFormHelpers.ReadJsonField(mPath, ""created"")")
    n = IL(cm, n, "            vDesc = KernelFormHelpers.ReadJsonField(mPath, ""description"")")
    n = IL(cm, n, "            vStale = KernelFormHelpers.ReadJsonField(mPath, ""resultsStale"")")
    n = IL(cm, n, "            vLastRun = KernelFormHelpers.ReadJsonField(mPath, ""lastRunAt"")")
    n = IL(cm, n, "            vDuration = KernelFormHelpers.ReadJsonField(mPath, ""runDuration"")")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "        lstVersions.AddItem vFolders(vi)")
    n = IL(cm, n, "        lstVersions.List(lstVersions.ListCount - 1, 1) = vDate")
    n = IL(cm, n, "        lstVersions.List(lstVersions.ListCount - 1, 2) = vDesc")
    n = IL(cm, n, "        lstVersions.List(lstVersions.ListCount - 1, 3) = IIf(StrComp(vStale, ""true"", vbTextCompare) = 0, ""Stale"", """")")
    n = IL(cm, n, "        lstVersions.List(lstVersions.ListCount - 1, 4) = vLastRun")
    n = IL(cm, n, "        lstVersions.List(lstVersions.ListCount - 1, 5) = vDuration")
    n = IL(cm, n, "    Next vi")
    n = IL(cm, n, "    Set fso = Nothing")
    n = IL(cm, n, "    On Error GoTo 0")
    n = IL(cm, n, "    If lstVersions.ListCount > 0 Then lstVersions.ListIndex = 0")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnSortDate_Click()")
    n = IL(cm, n, "    m_sortByDate = True")
    n = IL(cm, n, "    LoadVersionList")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnSortName_Click()")
    n = IL(cm, n, "    m_sortByDate = False")
    n = IL(cm, n, "    LoadVersionList")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnSave_Click()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 And Len(Trim(cmbWorkspace.Text)) = 0 Then")
    n = IL(cm, n, "        MsgBox ""Enter or select a workspace name."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    If Len(Trim(cmbWorkspace.Text)) > 0 Then")
    n = IL(cm, n, "        wsName = Trim(cmbWorkspace.Text)")
    n = IL(cm, n, "        If Left(wsName, 4) = ""[P] "" Then wsName = Mid(wsName, 5)")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        wsName = GetRealWSName()")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    KernelWorkspace.SaveWorkspace wsName")
    n = IL(cm, n, "    m_activeWS = wsName")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    Dim si As Long")
    n = IL(cm, n, "    For si = 0 To cmbWorkspace.ListCount - 1")
    n = IL(cm, n, "        If StrComp(cmbWorkspace.List(si), wsName, vbTextCompare) = 0 Then")
    n = IL(cm, n, "            cmbWorkspace.ListIndex = si")
    n = IL(cm, n, "            Exit For")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "    Next si")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnLoadAll_Click()")
    n = IL(cm, n, "    If lstVersions.ListIndex < 0 Or cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a version to load."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    Dim verName As String")
    n = IL(cm, n, "    verName = lstVersions.List(lstVersions.ListIndex, 0)")
    n = IL(cm, n, "    Dim verNum As Long")
    n = IL(cm, n, "    If Len(verName) > 1 Then verNum = CLng(Mid(verName, 2))")
    n = IL(cm, n, "    m_activeWS = wsName")
    n = IL(cm, n, "    m_activeVer = verName")
    n = IL(cm, n, "    Unload Me")
    n = IL(cm, n, "    KernelWorkspace.LoadWorkspace wsName, verNum")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnNewWS_Click()")
    n = IL(cm, n, "    Dim newName As String")
    n = IL(cm, n, "    newName = InputBox(""New workspace name:"", ""RDK -- New Workspace"")")
    n = IL(cm, n, "    If Len(Trim(newName)) = 0 Then Exit Sub")
    n = IL(cm, n, "    cmbWorkspace.AddItem Trim(newName)")
    n = IL(cm, n, "    cmbWorkspace.ListIndex = cmbWorkspace.ListCount - 1")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnBranch_Click()")
    n = IL(cm, n, "    If lstVersions.ListIndex < 0 Or cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a version to branch from."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim newName As String")
    n = IL(cm, n, "    newName = InputBox(""New branch name:"", ""RDK -- Branch"")")
    n = IL(cm, n, "    If Len(Trim(newName)) = 0 Then Exit Sub")
    n = IL(cm, n, "    Dim fromWS As String")
    n = IL(cm, n, "    fromWS = GetRealWSName()")
    n = IL(cm, n, "    Dim verName As String")
    n = IL(cm, n, "    verName = lstVersions.List(lstVersions.ListIndex, 0)")
    n = IL(cm, n, "    Dim verNum As Long")
    n = IL(cm, n, "    If Len(verName) > 1 Then verNum = CLng(Mid(verName, 2))")
    n = IL(cm, n, "    KernelWorkspace.BranchWorkspace Trim(newName), fromWS, verNum")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    Dim bi As Long")
    n = IL(cm, n, "    For bi = 0 To cmbWorkspace.ListCount - 1")
    n = IL(cm, n, "        If StrComp(cmbWorkspace.List(bi), Trim(newName), vbTextCompare) = 0 Then")
    n = IL(cm, n, "            cmbWorkspace.ListIndex = bi")
    n = IL(cm, n, "            Exit For")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "    Next bi")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnArchive_Click()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a workspace to archive."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    If optArchived.Value Then")
    n = IL(cm, n, "        If MsgBox(""Restore workspace '"" & wsName & ""' from archive?"", vbYesNo Or vbQuestion, ""RDK"") = vbNo Then Exit Sub")
    n = IL(cm, n, "        On Error Resume Next")
    n = IL(cm, n, "        Dim fso As Object")
    n = IL(cm, n, "        Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "        Dim root As String: root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "        fso.MoveFolder root & ""\workspaces\archive\"" & wsName, root & ""\workspaces\"" & wsName")
    n = IL(cm, n, "        Set fso = Nothing")
    n = IL(cm, n, "        On Error GoTo 0")
    n = IL(cm, n, "        MsgBox ""Workspace restored: "" & wsName, vbInformation, ""RDK""")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        If MsgBox(""Archive workspace '"" & wsName & ""'?"", vbYesNo Or vbQuestion, ""RDK"") = vbNo Then Exit Sub")
    n = IL(cm, n, "        On Error Resume Next")
    n = IL(cm, n, "        Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "        root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "        Dim archDir As String: archDir = root & ""\workspaces\archive""")
    n = IL(cm, n, "        If Not fso.FolderExists(archDir) Then fso.CreateFolder archDir")
    n = IL(cm, n, "        fso.MoveFolder root & ""\workspaces\"" & wsName, archDir & ""\"" & wsName")
    n = IL(cm, n, "        Set fso = Nothing")
    n = IL(cm, n, "        On Error GoTo 0")
    n = IL(cm, n, "        MsgBox ""Workspace archived: "" & wsName, vbInformation, ""RDK""")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnDelete_Click()")
    n = IL(cm, n, "    If lstVersions.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a version to delete."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    Dim verName As String")
    n = IL(cm, n, "    verName = lstVersions.List(lstVersions.ListIndex, 0)")
    n = IL(cm, n, "    If MsgBox(""Delete version "" & verName & "" from workspace '"" & wsName & ""'?"" & vbCrLf & ""This cannot be undone."", _")
    n = IL(cm, n, "              vbYesNo Or vbExclamation, ""RDK -- Delete Version"") = vbNo Then Exit Sub")
    n = IL(cm, n, "    On Error Resume Next")
    n = IL(cm, n, "    Dim fso As Object")
    n = IL(cm, n, "    Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "    Dim root As String: root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\"" & wsName")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive\"" & wsName")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim vDir As String: vDir = baseDir & ""\"" & verName")
    n = IL(cm, n, "    If fso.FolderExists(vDir) Then fso.DeleteFolder vDir, True")
    n = IL(cm, n, "    Set fso = Nothing")
    n = IL(cm, n, "    On Error GoTo 0")
    n = IL(cm, n, "    LoadVersionList")
    n = IL(cm, n, "    UpdateWSMeta")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnRename_Click()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a workspace to rename."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim oldName As String")
    n = IL(cm, n, "    oldName = GetRealWSName()")
    n = IL(cm, n, "    Dim newName As String")
    n = IL(cm, n, "    newName = InputBox(""New name for workspace '"" & oldName & ""':"", ""RDK -- Rename"", oldName)")
    n = IL(cm, n, "    If Len(Trim(newName)) = 0 Or StrComp(Trim(newName), oldName, vbTextCompare) = 0 Then Exit Sub")
    n = IL(cm, n, "    On Error Resume Next")
    n = IL(cm, n, "    Dim fso As Object")
    n = IL(cm, n, "    Set fso = CreateObject(""Scripting.FileSystemObject"")")
    n = IL(cm, n, "    Dim root As String: root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces""")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive""")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    fso.MoveFolder baseDir & ""\"" & oldName, baseDir & ""\"" & Trim(newName)")
    n = IL(cm, n, "    Set fso = Nothing")
    n = IL(cm, n, "    On Error GoTo 0")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnDesc_Click()")
    n = IL(cm, n, "    If lstVersions.ListIndex < 0 Then")
    n = IL(cm, n, "        MsgBox ""Select a version."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim curDesc As String")
    n = IL(cm, n, "    curDesc = lstVersions.List(lstVersions.ListIndex, 2)")
    n = IL(cm, n, "    Dim newDesc As String")
    n = IL(cm, n, "    newDesc = InputBox(""Description:"", ""RDK -- Edit Description"", curDesc)")
    n = IL(cm, n, "    If Len(newDesc) = 0 Then Exit Sub")
    n = IL(cm, n, "    Dim wsName As String")
    n = IL(cm, n, "    wsName = GetRealWSName()")
    n = IL(cm, n, "    Dim verName As String")
    n = IL(cm, n, "    verName = lstVersions.List(lstVersions.ListIndex, 0)")
    n = IL(cm, n, "    Dim root As String: root = ThisWorkbook.Path & ""\..""")
    n = IL(cm, n, "    Dim baseDir As String")
    n = IL(cm, n, "    If optActive.Value Then")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\"" & wsName")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        baseDir = root & ""\workspaces\archive\"" & wsName")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    Dim mPath As String: mPath = baseDir & ""\"" & verName & ""\manifest.json""")
    n = IL(cm, n, "    If Dir(mPath) <> """" Then")
    n = IL(cm, n, "        On Error Resume Next")
    n = IL(cm, n, "        Dim fn As Integer: fn = FreeFile")
    n = IL(cm, n, "        Dim content As String")
    n = IL(cm, n, "        Open mPath For Binary Access Read As #fn")
    n = IL(cm, n, "        content = Space$(LOF(fn))")
    n = IL(cm, n, "        Get #fn, , content")
    n = IL(cm, n, "        Close #fn")
    n = IL(cm, n, "        Dim Q As String: Q = Chr(34)")
    n = IL(cm, n, "        Dim oldPat As String")
    n = IL(cm, n, "        oldPat = Q & ""description"" & Q & "": "" & Q & curDesc & Q")
    n = IL(cm, n, "        Dim newPat As String")
    n = IL(cm, n, "        newPat = Q & ""description"" & Q & "": "" & Q & newDesc & Q")
    n = IL(cm, n, "        content = Replace(content, oldPat, newPat)")
    n = IL(cm, n, "        fn = FreeFile")
    n = IL(cm, n, "        Open mPath For Output As #fn")
    n = IL(cm, n, "        Print #fn, content")
    n = IL(cm, n, "        Close #fn")
    n = IL(cm, n, "        On Error GoTo 0")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    LoadVersionList")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnCompare_Click()")
    n = IL(cm, n, "    If lstVersions.ListCount < 2 Then")
    n = IL(cm, n, "        MsgBox ""Need at least 2 versions to compare."", vbExclamation, ""RDK""")
    n = IL(cm, n, "        Exit Sub")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    MsgBox ""Select two versions (hold Ctrl) and use Compare from the Snapshot Explorer (dev mode)."" & vbCrLf & _")
    n = IL(cm, n, "           ""Full workspace compare coming soon."", vbInformation, ""RDK""")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnMore_Click()")
    n = IL(cm, n, "    MoreActions.Show vbModal")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnPin_Click()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then Exit Sub")
    n = IL(cm, n, "    Dim wsN As String: wsN = GetRealWSName()")
    n = IL(cm, n, "    If KernelWorkspace.IsWorkspacePinned(wsN) Then")
    n = IL(cm, n, "        KernelWorkspace.UnpinWorkspace wsN")
    n = IL(cm, n, "    Else")
    n = IL(cm, n, "        KernelWorkspace.PinWorkspace wsN")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    LoadWorkspaceList")
    n = IL(cm, n, "    Dim si As Long")
    n = IL(cm, n, "    For si = 0 To cmbWorkspace.ListCount - 1")
    n = IL(cm, n, "        Dim chk As String: chk = cmbWorkspace.List(si)")
    n = IL(cm, n, "        If Left(chk, 4) = ""[P] "" Then chk = Mid(chk, 5)")
    n = IL(cm, n, "        If StrComp(chk, wsN, vbTextCompare) = 0 Then")
    n = IL(cm, n, "            cmbWorkspace.ListIndex = si")
    n = IL(cm, n, "            Exit For")
    n = IL(cm, n, "        End If")
    n = IL(cm, n, "    Next si")
    n = IL(cm, n, "End Sub")
    n = IL(cm, n, "")
    n = IL(cm, n, "Private Sub btnInspect_Click()")
    n = IL(cm, n, "    If cmbWorkspace.ListIndex < 0 Then Exit Sub")
    n = IL(cm, n, "    Dim wsN As String: wsN = GetRealWSName()")
    n = IL(cm, n, "    Dim inspVer As Long: inspVer = 0")
    n = IL(cm, n, "    If lstVersions.ListIndex >= 0 Then")
    n = IL(cm, n, "        Dim vn As String: vn = lstVersions.List(lstVersions.ListIndex, 0)")
    n = IL(cm, n, "        If Len(vn) > 1 Then inspVer = CLng(Mid(vn, 2))")
    n = IL(cm, n, "    End If")
    n = IL(cm, n, "    MsgBox KernelWorkspace.CheckWorkspaceCompleteness(wsN, inspVer), vbInformation, ""RDK -- "" & wsN")
    n = IL(cm, n, "End Sub")
End Sub


' =============================================================================
' FORM: MoreActions
' Small popup with buttons for secondary workspace actions.
' =============================================================================
Public Sub CreateMoreActions()
    Dim comp As Object
    Set comp = ThisWorkbook.VBProject.VBComponents.Add(3)
    comp.Name = "MoreActions"
    Dim d As Object: Set d = comp.designer
    comp.Properties("Caption") = "More Actions"
    comp.Properties("Width") = 180
    comp.Properties("Height") = 260
    KernelFormSetup.AddButton d, "btnMADelete", "Delete Version", 12, 10, 150, 28
    KernelFormSetup.AddButton d, "btnMAArchive", "Archive Workspace", 12, 44, 150, 28
    KernelFormSetup.AddButton d, "btnMARename", "Rename Workspace", 12, 78, 150, 28
    KernelFormSetup.AddButton d, "btnMADesc", "Edit Description", 12, 112, 150, 28
    KernelFormSetup.AddButton d, "btnMABranch", "Branch from Selected", 12, 146, 150, 28
    KernelFormSetup.AddButton d, "btnMACancel", "Cancel", 12, 194, 150, 26
    AddMoreActionsCode comp.CodeModule
End Sub

Private Sub AddMoreActionsCode(ByVal cm As Object)
    Dim n As Long: n = 1
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMADelete_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    WorkspaceExplorer.btnDelete_Click")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMAArchive_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    WorkspaceExplorer.btnArchive_Click")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMARename_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    WorkspaceExplorer.btnRename_Click")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMADesc_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    WorkspaceExplorer.btnDesc_Click")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMABranch_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    WorkspaceExplorer.btnBranch_Click")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnMACancel_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "End Sub")
End Sub


' =============================================================================
' FORM: AssumptionExplorer
' ListBox-based assumption manager with filter, detail panel, CRUD buttons.
' =============================================================================
Public Sub CreateAssumptionExplorer()
    Dim comp As Object
    Set comp = ThisWorkbook.VBProject.VBComponents.Add(3)
    comp.Name = "AssumptionExplorer"
    Dim d As Object: Set d = comp.Designer
    comp.Properties("Caption") = "Assumption Manager"
    comp.Properties("Width") = 620
    comp.Properties("Height") = 420

    ' --- Filter bar ---
    KernelFormSetup.AddOptionButton d, "optAll", "All", 12, 8, 40, 18
    KernelFormSetup.AddOptionButton d, "optHighSens", "High Sensitivity", 56, 8, 100, 18
    KernelFormSetup.AddOptionButton d, "optStale", "Stale (>90 days)", 160, 8, 100, 18
    KernelFormSetup.AddLabel d, "lblCount", "", 280, 10, 120, 14
    Dim cntCtrl As Object
    Set cntCtrl = d.Controls("lblCount")
    cntCtrl.Font.Size = 8
    cntCtrl.ForeColor = &H808080

    ' --- Assumption list (7 columns: ID, Category, Description, Confidence, Sensitivity, Owner, Reviewed) ---
    KernelFormSetup.AddListBox d, "lstAssumptions", 12, 30, 590, 200, 7, "35;70;200;60;60;50;70"

    ' --- Detail panel ---
    KernelFormSetup.AddLabel d, "lblDetail", "", 12, 236, 590, 50
    Dim detCtrl As Object
    Set detCtrl = d.Controls("lblDetail")
    detCtrl.Font.Size = 8
    detCtrl.ForeColor = &H404040
    detCtrl.WordWrap = True

    ' --- Action buttons ---
    KernelFormSetup.AddButton d, "btnAdd", "Add New", 12, 294, 80, 28
    KernelFormSetup.AddButton d, "btnEdit", "Edit", 98, 294, 70, 28
    KernelFormSetup.AddButton d, "btnArchive", "Archive", 174, 294, 70, 28
    KernelFormSetup.AddButton d, "btnReview", "Mark Reviewed", 250, 294, 100, 28
    KernelFormSetup.AddButton d, "btnClear", "Clear All", 356, 294, 70, 28
    KernelFormSetup.AddButton d, "btnRefresh", "Refresh", 530, 294, 70, 28

    AddAssumptionExplorerCode comp.CodeModule
End Sub

Private Sub AddAssumptionExplorerCode(ByVal cm As Object)
    If cm.CountOfLines > 0 Then cm.DeleteLines 1, cm.CountOfLines
    Dim n As Long: n = 1
    n = KernelFormSetup.IL(cm, n, "Option Explicit")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub UserForm_Initialize()")
    n = KernelFormSetup.IL(cm, n, "    optAll.Value = True")
    n = KernelFormSetup.IL(cm, n, "    LoadList")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub optAll_Click(): LoadList: End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub optHighSens_Click(): LoadList: End Sub")
    n = KernelFormSetup.IL(cm, n, "Private Sub optStale_Click(): LoadList: End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub LoadList()")
    n = KernelFormSetup.IL(cm, n, "    lstAssumptions.Clear")
    n = KernelFormSetup.IL(cm, n, "    lblDetail.Caption = """"")
    n = KernelFormSetup.IL(cm, n, "    On Error Resume Next")
    n = KernelFormSetup.IL(cm, n, "    Dim wsC As Worksheet")
    n = KernelFormSetup.IL(cm, n, "    Set wsC = ThisWorkbook.Sheets(""Config"")")
    n = KernelFormSetup.IL(cm, n, "    If wsC Is Nothing Then Exit Sub")
    n = KernelFormSetup.IL(cm, n, "    Dim sr As Long")
    n = KernelFormSetup.IL(cm, n, "    sr = KernelConfigLoader.FindSectionStart(wsC, ""=== ASSUMPTIONS_CONFIG ==="")")
    n = KernelFormSetup.IL(cm, n, "    If sr = 0 Then Exit Sub")
    n = KernelFormSetup.IL(cm, n, "    Dim dr As Long: dr = sr + 2")
    n = KernelFormSetup.IL(cm, n, "    Dim cnt As Long: cnt = 0")
    n = KernelFormSetup.IL(cm, n, "    Do While Len(Trim(CStr(wsC.Cells(dr, 1).Value))) > 0")
    n = KernelFormSetup.IL(cm, n, "        If Left(CStr(wsC.Cells(dr, 1).Value), 3) = ""==="" Then Exit Do")
    n = KernelFormSetup.IL(cm, n, "        Dim aID As String: aID = CStr(wsC.Cells(dr, 1).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aCat As String: aCat = CStr(wsC.Cells(dr, 2).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aDesc As String: aDesc = CStr(wsC.Cells(dr, 5).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aConf As String: aConf = CStr(wsC.Cells(dr, 8).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aSens As String: aSens = CStr(wsC.Cells(dr, 9).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aOwner As String: aOwner = CStr(wsC.Cells(dr, 11).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim aRev As String: aRev = CStr(wsC.Cells(dr, 12).Value)")
    n = KernelFormSetup.IL(cm, n, "        Dim show As Boolean: show = True")
    n = KernelFormSetup.IL(cm, n, "        If Left(aCat, 9) = ""ARCHIVED-"" Then show = False")
    n = KernelFormSetup.IL(cm, n, "        If optHighSens.Value And aSens <> ""High"" Then show = False")
    n = KernelFormSetup.IL(cm, n, "        If optStale.Value Then")
    n = KernelFormSetup.IL(cm, n, "            If Len(aRev) > 0 Then")
    n = KernelFormSetup.IL(cm, n, "                If DateDiff(""d"", CDate(aRev), Date) <= 90 Then show = False")
    n = KernelFormSetup.IL(cm, n, "            End If")
    n = KernelFormSetup.IL(cm, n, "        End If")
    n = KernelFormSetup.IL(cm, n, "        If show Then")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.AddItem aID")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 1) = aCat")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 2) = aDesc")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 3) = aConf")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 4) = aSens")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 5) = aOwner")
    n = KernelFormSetup.IL(cm, n, "            lstAssumptions.List(cnt, 6) = aRev")
    n = KernelFormSetup.IL(cm, n, "            cnt = cnt + 1")
    n = KernelFormSetup.IL(cm, n, "        End If")
    n = KernelFormSetup.IL(cm, n, "        dr = dr + 1")
    n = KernelFormSetup.IL(cm, n, "    Loop")
    n = KernelFormSetup.IL(cm, n, "    lblCount.Caption = cnt & "" assumptions""")
    n = KernelFormSetup.IL(cm, n, "    On Error GoTo 0")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub lstAssumptions_Click()")
    n = KernelFormSetup.IL(cm, n, "    If lstAssumptions.ListIndex < 0 Then Exit Sub")
    n = KernelFormSetup.IL(cm, n, "    Dim aID As String: aID = lstAssumptions.List(lstAssumptions.ListIndex, 0)")
    n = KernelFormSetup.IL(cm, n, "    On Error Resume Next")
    n = KernelFormSetup.IL(cm, n, "    Dim wsC As Worksheet")
    n = KernelFormSetup.IL(cm, n, "    Set wsC = ThisWorkbook.Sheets(""Config"")")
    n = KernelFormSetup.IL(cm, n, "    Dim sr As Long")
    n = KernelFormSetup.IL(cm, n, "    sr = KernelConfigLoader.FindSectionStart(wsC, ""=== ASSUMPTIONS_CONFIG ==="")")
    n = KernelFormSetup.IL(cm, n, "    If sr = 0 Then Exit Sub")
    n = KernelFormSetup.IL(cm, n, "    Dim dr As Long: dr = sr + 2")
    n = KernelFormSetup.IL(cm, n, "    Do While Len(Trim(CStr(wsC.Cells(dr, 1).Value))) > 0")
    n = KernelFormSetup.IL(cm, n, "        If Left(CStr(wsC.Cells(dr, 1).Value), 3) = ""==="" Then Exit Do")
    n = KernelFormSetup.IL(cm, n, "        If CStr(wsC.Cells(dr, 1).Value) = aID Then")
    n = KernelFormSetup.IL(cm, n, "            lblDetail.Caption = ""Rationale: "" & CStr(wsC.Cells(dr, 6).Value) & vbCrLf & _")
    n = KernelFormSetup.IL(cm, n, "                ""Source: "" & CStr(wsC.Cells(dr, 7).Value) & ""  |  Impact: "" & CStr(wsC.Cells(dr, 10).Value) & vbCrLf & _")
    n = KernelFormSetup.IL(cm, n, "                ""History: "" & CStr(wsC.Cells(dr, 13).Value)")
    n = KernelFormSetup.IL(cm, n, "            Exit Do")
    n = KernelFormSetup.IL(cm, n, "        End If")
    n = KernelFormSetup.IL(cm, n, "        dr = dr + 1")
    n = KernelFormSetup.IL(cm, n, "    Loop")
    n = KernelFormSetup.IL(cm, n, "    On Error GoTo 0")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnAdd_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    KernelAssumptions.AddAssumption")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnEdit_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    KernelAssumptions.EditAssumption")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnArchive_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    KernelAssumptions.ArchiveAssumption")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnReview_Click()")
    n = KernelFormSetup.IL(cm, n, "    Dim stale As String")
    n = KernelFormSetup.IL(cm, n, "    stale = KernelAssumptions.GetStaleAssumptions(90)")
    n = KernelFormSetup.IL(cm, n, "    If Len(stale) = 0 Then")
    n = KernelFormSetup.IL(cm, n, "        MsgBox ""All assumptions reviewed within 90 days."", vbInformation, ""RDK""")
    n = KernelFormSetup.IL(cm, n, "    Else")
    n = KernelFormSetup.IL(cm, n, "        MsgBox ""Stale: "" & stale, vbInformation, ""RDK""")
    n = KernelFormSetup.IL(cm, n, "    End If")
    n = KernelFormSetup.IL(cm, n, "    LoadList")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnClear_Click()")
    n = KernelFormSetup.IL(cm, n, "    Unload Me")
    n = KernelFormSetup.IL(cm, n, "    KernelAssumptions.ShowAssumptionManager")
    n = KernelFormSetup.IL(cm, n, "End Sub")
    n = KernelFormSetup.IL(cm, n, "")
    n = KernelFormSetup.IL(cm, n, "Private Sub btnRefresh_Click()")
    n = KernelFormSetup.IL(cm, n, "    KernelAssumptions.GenerateAssumptionsRegister")
    n = KernelFormSetup.IL(cm, n, "    LoadList")
    n = KernelFormSetup.IL(cm, n, "End Sub")
End Sub


